### ISSUE TITLE
How to Add Window on pressing toggle button

### ISSUE THREAD

**Issue by svkvarun43** [bludeck/imgui-animated#1]
Hi 

How do I open a window when I have pressed the toggle button ( moved to right ) with the syntax you have provided

Currently I have

`if(ImGui::Toggle("Toggle button", &connections_window));`

which opens a window instantly without me pressing the toggle button.

This would be really helpful

Thankyou

**Comment by bludeck** [comment]
Are you checking for value of `connections_window` before drawing a window?

**Comment by bludeck** [comment]
Closed due to inactivity.
