### ISSUE TITLE
Error: Unresolved Externals

### ISSUE THREAD

**Issue by kocasa** [bludeck/imgui-animated#2]
I downloaded and pasted in both ```imgui_animated.cpp``` and ```imgui_animated.h``` and included them in my ImGui project. I then tried to do a test run just to mess around with my newly acquired functions, but I'm getting an error. 
![image](https://user-images.githubusercontent.com/68087868/176780781-cec53468-798b-4929-8a20-0c0492eed931.png)
Does anyone know how to fix this?

**Comment by iProB1** [comment]
its alr defined at imgui.h 

Change Toggle to ToggleAnim its all

**Comment by bludeck** [comment]
@kocasa Are you sure that you included imgui_animated.cpp?

@iProB1 Can you link me where it is defined in imgui? Can't find it
> its alr defined at imgui.h
> 
> Change Toggle to ToggleAnim its all

**Comment by bludeck** [comment]
No updates for few months, closing now
