### ISSUE TITLE
'LastItemData': is not a member of 'ImGuiContext'

### ISSUE THREAD

**Issue by xorCoding** [bludeck/imgui-animated#3]
Hi, i get this error when i try to build the imgui_animated.cpp file
![error](https://user-images.githubusercontent.com/107063555/179348368-0e5c14de-23d6-4cd0-b4f5-9291c6f9072b.png)
Anyone knows how can i solve?

**Comment by wyxather** [comment]
You're probably using different version of ImGui. Check the latest version and see if there are any changes related to ImGuiContext.

**Comment by bludeck** [comment]
You are using too old version of ImGui for which we cannot provide compatibility.
